[bugfix][workflow] comment too long part

diff --git a/.github/workflows/init-deploy.yml b/.github/workflows/init-deploy.yml
--- a/.github/workflows/init-deploy.yml
+++ b/.github/workflows/init-deploy.yml
@@ -12,6 +12,15 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
+      - name: build low privilege kube config
+        run: |
+          set -euo pipefail
+          bash deploy/release-v0.1.0/kube/gen_config.sh 
+        # generate kubeconfig-safezone.yaml
+      
+      - name: set kubeconfig env to new config
+        run: echo "KUBECONFIG=kubeconfig-safezone.yaml" >> $GITHUB_ENV
+
       - name: Check K8s context
         run: kubectl config get-contexts
 
@@ -49,13 +58,13 @@ jobs:
           set -euo pipefail
           kubectl apply -n gitops -f deploy/release-v0.1.0/argocd/staging/apps/safezone-core-seed.yaml
           
-      - name: Wait for core-seed job Create
-        run: sleep 3
+      # - name: Wait for core-seed job Create
+      #   run: sleep 3
       
-      - name: Wait for core-seed job completion
-        run: |
-          set -euo pipefail
-          kubectl wait --for=condition=complete --timeout=5400s job/safezone-core-seed -n safezone || (echo "Job safezone-core-seed failed" && exit 1)
+      # - name: Wait for core-seed job completion
+      #   run: |
+      #     set -euo pipefail
+      #     kubectl wait --for=condition=complete --timeout=6000s job/safezone-core-seed -n safezone || (echo "Job safezone-core-seed failed" && exit 1)
 
       - name: Deploy argocd application for phase ui
         run: |
